### ISSUE TITLE
Brainstorm para indicações de ideias em projetos de software

### ISSUE THREAD

**Issue by radamesp7** [radamesp7/AbexII_G4_2024#1]
O brainstorming se aplica a disciplina de aprendizado baseado em experiências, onde os alunos em grupos indicam o que pode ser uma ideia de problema que possa ser solucionado com o desenvolvimento de um aplicativo de software e que tem uma finalidade prática. O brainstoriming deve gerar ideias entre os membros do grupo e precisa que se use como base o github para que possam trabalhar como grupo de trabalho e registrar as ideias conforme forem gerando as mesmas.

 Lista de Ideias:

**Comment by BernardoUNO** [comment]
Ideias:
1- Gestão de inventário - desenvolver um aplicativo que monitore o estoque

2- Apoio rápida a emergências - aplicativo para reportar emergências rapidamente enviando alertas para equipes responsáveis, e também oferecer informações úteis para aquela situação crítica

3- Sistema para ajudar no planejamento de viagens 

4- Gerenciamento de documentos - aplicativo que ajude a acessar documentos de forma eficiente 

5- Sistema que controle a qualidade de produção - monitore a produção com alertas e relatórios sobre falhas

6- Sistema de gerenciamento de manutenções - sistema que organize e registre solicitações de manutenção e seu progresso 

7- Organização de tarefas domésticas - aplicativo para organizar e distribuir tarefas, definindo prazos e mandando lembretes para todos os envolvidos.

8- Apoio psicológico - tenha notícias e informações importantes que ajudem no apoio emocional e um chat com uma IA para poder ter um conversa
